version: "3.8"
services:
    api:
        build: ./api
        restart: always
        volumes:
            - ./api/src:/code # this mounts the local directory ""./application" to the container's directory "/code"
        ports:
            - 5000:5000
            
    
    rabbitmq:
        image: rabbitmq:3-management
        container_name: 'rabbitmq'
        ports:
            - 5672:5672
            - 15672:15672
        volumes:
            - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
            - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq